### ISSUE TITLE
Space not shown

### ISSUE THREAD

**Issue by thizisarun** [timfreiheit/MathJaxAndroid#1]
Thanks for giving this example. I have some query. If display plain text with formula, the white space between plain text is trimmed . My Example is 

Input : Hello world (\infty) hello world
Output : Helloworld∞helloworld

How can i give space between words?

**Comment by timfreiheit** [comment]
Hi,
the problem was that the given input was completely treated as math input.
I updated the example to support inline math.
All math parts must be surrounded by \( and \) now.
Your example would look like this: `Hello world \\((\infty)\\) hello world`
I hope this helps you.
